=== santisanudo13/ProcesosSantiCarlos/Practica1/ImpuestoCirculacion/src/main/resources/ImpuestoCirculacion.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0" targetNamespace="http://www.example.org/ss/impuestoCirculacion" xmlns:tns="http://www.example.org/ss/impuestoCirculacion" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="ayuntamiento">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contribuyente" type="tns:Contribuyente" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Motocicleta">
    <xs:complexContent>
      <xs:extension base="tns:Vehiculo">
        <xs:sequence/>
        <xs:attribute name="cilindrada" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Vehiculo" abstract="true">
    <xs:sequence/>
    <xs:attribute name="matricula" type="xs:string" use="required"/>
    <xs:attribute name="Fecha1Matriculacion" type="xs:date" use="required"/>
  </xs:complexType>

  <xs:complexType name="Furgoneta">
    <xs:complexContent>
      <xs:extension base="tns:Vehiculo">
        <xs:sequence/>
        <xs:attribute name="potencia" type="xs:double" use="required"/>
        <xs:attribute name="comercial" type="xs:boolean" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Turismo">
    <xs:complexContent>
      <xs:extension base="tns:Vehiculo">
        <xs:sequence/>
        <xs:attribute name="potencia" type="xs:double" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Contribuyente">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="turismo" type="tns:Turismo"/>
        <xs:element name="furgoneta" type="tns:Furgoneta"/>
        <xs:element name="motocicleta" type="tns:Motocicleta"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="Nombre" type="xs:string" use="required"/>
    <xs:attribute name="Apellido1" type="xs:string" use="required"/>
    <xs:attribute name="Apellido2" type="xs:string" use="required"/>
    <xs:attribute name="dni" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== santisanudo13/ProcesosSantiCarlos/Practica1/ImpuestoCirculacion/src/main/resources/ayuntamiento.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:ayuntamiento xmlns:tns="http://www.example.org/ss/impuestoCirculacion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ss/impuestoCirculacion.xsd ">
  
  <tns:contribuyente Apellido1="Gómez" Apellido2="Cobo" Nombre="Víctor" dni="72189333S">
    <tns:turismo Fecha1Matriculacion="2012-12-01" matricula="6541HHB" potencia="9"/>
    <tns:turismo Fecha1Matriculacion="2012-11-12" matricula="6462DTF" potencia="13"/>
  </tns:contribuyente>
  
  <tns:contribuyente Apellido1="Muñiz" Apellido2="Revuelta" Nombre="Alba" dni="72345121A">
    <tns:turismo Fecha1Matriculacion="2009-01-01" matricula="3441DDB" potencia="11"/>
    <tns:motocicleta Fecha1Matriculacion="2012-11-12" matricula="1232HHT" cilindrada="1200"/>
  </tns:contribuyente>
  
   <tns:contribuyente Apellido1="Grillo" Apellido2="Saltamontes" Nombre="Pepito" dni="71345631P">
    <tns:turismo Fecha1Matriculacion="2005-01-01" matricula="3247BBD" potencia="22"/>
    <tns:motocicleta Fecha1Matriculacion="2012-05-22" matricula="9224HGH" cilindrada="1200"/>
    <tns:furgoneta Fecha1Matriculacion="2014-01-01" matricula="3680DBD" potencia="15" comercial="true"/>
  </tns:contribuyente>
  
   <tns:contribuyente Apellido1="Menta" Apellido2="Perez" Nombre="Aitor" dni="71674631F">
    <tns:turismo Fecha1Matriculacion="2012-11-01" matricula="7847GGD" potencia="3"/>
    <tns:motocicleta Fecha1Matriculacion="2009-05-22" matricula="9147HDD" cilindrada="250"/>
    <tns:turismo Fecha1Matriculacion="2011-01-01" matricula="4893DBD" potencia="19"/>
  </tns:contribuyente>
  
   <tns:contribuyente Apellido1="Rivas" Apellido2="Cobo" Nombre="Amador" dni="78934831M">
    <tns:turismo Fecha1Matriculacion="2004-12-01" matricula="9424BGD" potencia="17"/>
    <tns:motocicleta Fecha1Matriculacion="2011-05-12" matricula="1687HGD" cilindrada="600"/> 
  </tns:contribuyente>
  
   <tns:contribuyente Apellido1="Marquez" Apellido2="Pedrosa" Nombre="Jorge" dni="73951831H">
   	<tns:motocicleta Fecha1Matriculacion="2009-03-11" matricula="1237HTD" cilindrada="120"/> 
    <tns:motocicleta Fecha1Matriculacion="2014-05-18" matricula="2807GFT" cilindrada="500"/> 
  </tns:contribuyente>
  
   <tns:contribuyente Apellido1="Lopez" Apellido2="Revuelta" Nombre="Segismundo" dni="78493121S">
    <tns:furgoneta Fecha1Matriculacion="2008-06-01" matricula="3543DDF" potencia="12" comercial="false"/>
    <tns:motocicleta Fecha1Matriculacion="2003-07-06" matricula="1707BBG" cilindrada="200"/> 
  </tns:contribuyente>
  
</tns:ayuntamiento>
